$ANSIBLE_VAULT;1.1;AES256
66383237613538303937616132343837643030386165373233623930353337323835303461303532
3136383637656335386337623065376334383630383237300a386536323861623730356435306165
64373432303861373537303865326361373730616138376561383564373865303538353733386261
6165353362373338640a386138326137613735636139303238623937323765373537346532323161
37326135613635356232633462343233373437303861393863353866613439626162616236653761
38366132623730306235373865623430626661373932373533383836396637613734323738396136
38363238373462396661333363343538383039646435396361626163373034393230396364343039
38616161396234353338383035613538633666363439613538393836663066396138613864323232
66663530396232313530343066303036646466383637303066633830656265656536343863666533
35383034666366653730353263636165643535333066643334306536663030303334353430356665
33306638653630363333303365653730373039323030303034303830353039343530666561353737
37366266656530303234363564306166646366306430303664373366356435306660353463666035
30363434333761343530343734373065373666376465343730653232323034303036343463626562
66363065373565666030663664306430373065303030656535363730303530323234303034323230
34656530323737343537343534363534303737343537343534363534303737343537343534363534
30373734353537343534133336334353838303964643539630373734353734353436353430373743
34353734363534303737343537343534363534303737343537343534363534303737343537343534
36353430373734353734353436353430373734353734353436353430373734353734353436353430
37373435373435343635343037373435373435343635343037373435373435343635343037373435
37343534363534303737343537343534363534394831409366437234363534303737343537343534
36353430373542953734353436353430373734353734353436353430373734353734353436353403
37343537343534363534303737343537331231233635343037373435373435036353430373734353
435343635343037373435373435343635343037373435373435343635343037